### ISSUE TITLE
Investigate deployment

### ISSUE THREAD

**Issue by shuhaowu** [shuhaowu/projecto#13]
At the end of the day, we need to deploy the app. Options to deploy:
1. Debian packaging (our target platform is debian)
2. Using ansible for deployment

Blocked by #33

**Comment by travellingprog** [comment]
Don't know how, but Meteor is able to install itself [with a single curl command](http://docs.meteor.com/#quickstart) on any platform it supports (Mac OSX and any Linux x86/x86_64 OS). So that might be another option worth investigating.

**Comment by shuhaowu** [comment]
We have a relatively special stack. The target platform is a 512MB 
Xen/KVM instance (I have one on spare) with Debian Wheezy.

A good option would be Debian packaging, there are also other methods 
like Fabric, and so forth.

Gotta do this right! :P

Shuhao

**Comment by shuhaowu** [comment]
I've gotten a KVM server. It should serve our needs. Got it for really cheap today.

**Comment by shuhaowu** [comment]
So I have a rough outline on how deployment will work (You probably don't care about this, but it is here if you want to know):
- We will have two servers: staging and production.
  - These two servers are identical in spec (512MB KVM running Debian Wheezy) and they are in a Buffalo data center.
  - The production database is synced to staging periodically so we can test on a separate database.
  - I'll still need to investigate how to do backups, but hopefully that will not be too difficult.
  - Staging will be at staging.<ourdomain>.com and production will be at ourdomain.com. Production will have SSL enabled while staging will not have that. This means when we link external resources we should link with https and not http. We won't be able to catch those until production.
- We will be using an [ansible](http://www.ansibleworks.com/) playbook to automate the deploy process

Deployment should be fairly simple with this setup and the proper ansible playbook. This playbook will not be in this repository as there are more sensitive data in there. 

Until we setup something where we can deploy via a web url, I will be the only one who can deploy (I have root to the boxes).

I will close this bug once I deploy both staging and production

**Comment by shuhaowu** [comment]
Investigating into this right now.

**Comment by shuhaowu** [comment]
So I have the first part of the automated deployment setup. Still need process supervision and testing the overall system.

If you want access to the deploy files/config files, let me know (or just give me your id_rsa.pub so I can add you into the system)

**Comment by shuhaowu** [comment]
This is ... kinda done. The deploy scripts are very flaky and not very robust..

It works though. Demo at http://getprojecto.ml (this will be our staging site url). 

Again, access to the provisioning files and scripts needs to go through a private repo hosted by me.

**Comment by shuhaowu** [comment]
Actually there's still a lot of issues with deployment. I'm going to reopen this but it is not urgent right now.

**Comment by shuhaowu** [comment]
I think I got this. At least for staging. Don't have a certificate yet, though.
