### ISSUE TITLE
Move away from Flask-Classy

### ISSUE THREAD

**Issue by shuhaowu** [shuhaowu/projecto#16]
Flask-classy does not actually help us that much. We should look into an alternative tool or create our own to structure the code to be better.

**Comment by travellingprog** [comment]
What are you looking for in an alternative tool?

**Comment by shuhaowu** [comment]
Unsure yet. Right now Flask-Classy provides nothing to us and really is 
a burden (I filed some bugs iwth them but it might be a limitation of 
their library).

I was looking through some and it seem like most have many limitations. 
We might be better forking one or rolling our own (for API rate limit 
and such)

Shuhao

**Comment by shuhaowu** [comment]
General discussions over how the backend cannot scale well when it is laid out like that should begin right about now as well...

Though we might be tempted to ignore that as I hope to release a version (probably without the file manager/dropbox functionality) _soon_.

**Comment by shuhaowu** [comment]
Last mail spam for the day: 

After some further evaluation of Flask-Classy I don't think we can continue with it. My current recommendation is to break out the views inside `v_api_v1.py` into a folder `apiv1` in the blueprints folder (however those won't be autoloaded). `v_api_v1.py` will then setup everything smartly (instead of having a class and using object instances, we just use a module and its methods. This way all of the decorators works nicely)

Proposed structure:

```
 blueprints
 \
  |---v_api_v1.py
  |---apiv1
   \
   |---__init__.py
   |---todo.py
   |---feed.py 
   ... etc
```

In each file under apiv1:

```
def get(id):
  # code

def post(id):
  # code

meta = {
  "base_url": "/project/<project_id>/todos",
  "methods": {
    get: ("/", ["GET"]),
    post: ("/", ["POST"])
  }
}
```

This syntax feels verbose... I don't see it being possible to retain magical decorators _AND_ have nice syntax though. (Perhaps the problem lies in the magical decorators).

We could also do autodiscovery for get, post, delete, and put. Rest will be up to the user? Anything magical would pretty much screw up other properties we want to have (such as magical decorators, and I think they're more important as it actually save us a lot of duplicate logic that may not be trivial (`@route` is fairly trivial))

Any other proposed syntax?

**Comment by shuhaowu** [comment]
Alright. Encountering some issues while dealing with archived todos relating to this. Gonna take this bug first.

**Comment by shuhaowu** [comment]
Alright. Major restructure of everything is pending. Here's the generally outline:
1. `v_api_v1.py` will be broken into a module called `apiv1`. This module is configured in the settings.
2. Inside `apiv1`, there will be many modules (folders) for each feature. For example, the feed will get the module `apiv1.feed`.
3. Inside `apiv1/feed/`, there will be an `api.py` file. Inside this, there is a global variable `blueprint` and `meta`. This is to be imported and registered to the application.
4. Inside `apiv1/feed`, there will be a `static` folder. All of the files that currently live in places like `static/js/develop` will move there. So will things like CSS.

So things that needs to be touched other than just `v_api_v1.py`:
- Code to figure out assets: `projecto/extensions.py`
- Code to figure out imports: `projecto/__init__.py`
- Front end template code to dynamically create header links, include JS files: `templates/master.html`
- Reorganize CSS file into multiple CSS files: `static/stylesheets/app.css`
- Settings to get the api modules to import: `settings.py`

Other things to note:
- Compiled assets will live at the same location (/static/app.js, /static/app.css I believe)
- Using this new architecture, we should be able to eventually have plugins to projecto (imagine third party adding in a apiv1 module)
- `apiv1` is configurable. So it is possible we can use `apiv2` later. Also, the module `apiv1` will have a route base that all submodules extends from.
- Blueprints inside apiv1 needs to declare things like `static_url_path` and `static_folder`. `static_url_path` should be `/static/modulename`

**Comment by shuhaowu** [comment]
@tmzhuang, @abhinavthukral28: If you guys are still working on this. Please do not make any major changes and take a note at above. After this, projecto's code base should be much less confusing.
