### ISSUE TITLE
Angular is not working well in the Feed page

### ISSUE THREAD

**Issue by travellingprog** [shuhaowu/projecto#19]
The Angular stuff in the Feed page is not working well, at the very least not in Chrome. 
1. The text within the textarea for new posts is not being linked to newpost. 
2. ng-submit is not preventing the Post button from reloading the page.

Here's [screenshots of the browser and server terminal](http://imgur.com/a/fivcN)

**Comment by shuhaowu** [comment]
That is strange. I cannot reproduce what you see. I do have an issue where if I press post, I can't see the Comment link on the post.

Are you sure all the resources have loaded successfully?

**Comment by travellingprog** [comment]
guess it was issue 19 not 18 lol i'll be more careful when naming my branches next time

**Comment by shuhaowu** [comment]
It's fine. No worries.
