### ISSUE TITLE
Landing pages, about pages, technology pages, privacy policy, terms of service.

### ISSUE THREAD

**Issue by shuhaowu** [shuhaowu/projecto#22]
So we need to expand these pages to look somewhat well. I nominate @tmzhuang for this task as he is just starting out and I feel like this would be an excellent exercise to get familiar with some of the technologies involved with web development. I will help out if he takes on these tasks.

Before we can close this, here are the list of things to be done:
- [ ] Landing page: We need a pretty looking landing page. There are plenty of these to look at on the internet (Github, Bitbucket, any Show HN website that requires payment would be cool, as we might do the same).
- [ ] About page: Just a quick about on what this project is all about and what not. Again, examples all over the interwebs (I think [Foundation's page](http://foundation.zurb.com/case-jacquelinewest.php) is a good reference for this, and maybe other pages too). Show that this is a side project by a couple of people, etc.
- [ ] Technology page: spill that we are going to be an open source project, list some tech we use and what not. 
- [ ] Privacy policy: I think Mozilla has a template.
- [ ] Terms of service: since we are providing a SaaS, I think we need this.

All in all most of these pages contain HTML + some CSS. It's possible that we might throw in some JavaScript. However, all these pages live **outside** of the angular world (that is, angular are not even included and to navigate from page to page you have to refresh).

**Comment by shuhaowu** [comment]
This is a big item! We need to this for demo day in 19 days. 

Speaking of which: DEMO DAY IN 19 DAYS OMAIGAWD. AADFJALK;JFD

**Comment by abhinavthukral28** [comment]
Ok I am on it
