### ISSUE TITLE
New Todo's new tags are not added to the Filter checkbox list immediately

### ISSUE THREAD

**Issue by travellingprog** [shuhaowu/projecto#26]
When you create a new Todo, and you assign it new tags, those tags don't show up in the the checkbox list of Filters until you refresh the page.

**Comment by shuhaowu** [comment]
Yeah. There are a lot of bugs in that department.

One thing that we might seriously consider doing after a couple bug fixes is tests. I have broken features after I fixed a bug.

Also, see #2

**Comment by travellingprog** [comment]
Also, the filters should be presented in some sorted manner. Could be alphabetical to start with, and then we'd add other sort options at a later time

**Comment by shuhaowu** [comment]
Right now it's reverse ordered by creation date i think.

So here's the decision: we could stop doing pagination on the server side and just return _all data_ and let the browser/JS do the pagination/sorting.

We could also implement something where the server does the sorting and the pagination.

The client side sorting is less load on the server, but bigger download.

The server side sorting is less load on the client and less download, but bigger load on the server.

The trick here is are there a lot of cases where people would have thousands of todos and causes a huge download? And even if that is the case, will the download break a 3 digits worth of KBs?

**Comment by travellingprog** [comment]
> Right now it's reverse ordered by creation date i think.

Nah, it's all over the place. Just to clarify, I was talking about the list of tags in the Filter box, on the left. For example, the last tag I made is 4th on the list.

We should set up a tests that create todo lists of varying sizes, and see how big the download size is for each list. Can't really make a decision without any measurement.

If it does turn out to be signification, I think pagination (and so sorting as well) should be mostly client-side for small amount of todos, mostly server-side after a certain amount.

There really could be a lot of todos, so it makes sense to only send part of them in that case.But I suspect that in _most_ cases, there will be under, say, 200 todos. So we could make a call to the server that initially retrieves up to the last 200 todos, and also the total number of todos. That gives us enough todos for the 10 first pages. When the user goes to page 11 (or skips to any page above 10), we send another call to the server to, again, get up to 200 todos. This would make the UI feel really fast most of the time.

With sorting, we check the number of total todos. Under 200? do it client-side (fast UI). Over 200? Call the server, get up to the latest 200 todos with the current filter settings.

**Comment by shuhaowu** [comment]
1kb is roughly 1000 characters. 1000 characters are roughly 100-200 words ish. Assuming each todos has about 200 words, 1000 todos would be 1MB.

Now not all issues will hit that much. The problem here is we can't measure until we see real world use cases.

The one thing we could do is not return the comments (whenever we implement that) with the todos when we filter/list them and only when we explicitly request for them.

**Comment by shuhaowu** [comment]
Is this done?

**Comment by shuhaowu** [comment]
Fixed this via #105, too!
